// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pb/blackjack.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suit          string                 `protobuf:"bytes,1,opt,name=suit,proto3" json:"suit,omitempty"`      // "H" (Corazones), "D" (Diamantes), "C" (Tréboles), "S" (Picas)
	Rank          string                 `protobuf:"bytes,2,opt,name=rank,proto3" json:"rank,omitempty"`      // "2".."10", "J", "Q", "K", "A"
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`   // Valor numérico principal (1..11)
	Hidden        bool                   `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"` // True si la carta está oculta (dealer)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_pb_blackjack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blackjack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_pb_blackjack_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetSuit() string {
	if x != nil {
		return x.Suit
	}
	return ""
}

func (x *Card) GetRank() string {
	if x != nil {
		return x.Rank
	}
	return ""
}

func (x *Card) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Card) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

type SubHand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 0 para mano principal, 1+ para split
	Cards          []*Card                `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	BetAmountCents int64                  `protobuf:"varint,3,opt,name=bet_amount_cents,json=betAmountCents,proto3" json:"bet_amount_cents,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "active", "stand", "bust", "blackjack", "doubled", "settled"
	Result         string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"` // "win", "lose", "push", "blackjack_win", "surrender"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubHand) Reset() {
	*x = SubHand{}
	mi := &file_pb_blackjack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubHand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubHand) ProtoMessage() {}

func (x *SubHand) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blackjack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubHand.ProtoReflect.Descriptor instead.
func (*SubHand) Descriptor() ([]byte, []int) {
	return file_pb_blackjack_proto_rawDescGZIP(), []int{1}
}

func (x *SubHand) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SubHand) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *SubHand) GetBetAmountCents() int64 {
	if x != nil {
		return x.BetAmountCents
	}
	return 0
}

func (x *SubHand) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubHand) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CreateHandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BetAmountCents int64                  `protobuf:"varint,2,opt,name=bet_amount_cents,json=betAmountCents,proto3" json:"bet_amount_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateHandRequest) Reset() {
	*x = CreateHandRequest{}
	mi := &file_pb_blackjack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHandRequest) ProtoMessage() {}

func (x *CreateHandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blackjack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHandRequest.ProtoReflect.Descriptor instead.
func (*CreateHandRequest) Descriptor() ([]byte, []int) {
	return file_pb_blackjack_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHandRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateHandRequest) GetBetAmountCents() int64 {
	if x != nil {
		return x.BetAmountCents
	}
	return 0
}

type CreateHandResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HandId            string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	SubHands          []*SubHand             `protobuf:"bytes,2,rep,name=sub_hands,json=subHands,proto3" json:"sub_hands,omitempty"`
	DealerVisibleCard *Card                  `protobuf:"bytes,3,opt,name=dealer_visible_card,json=dealerVisibleCard,proto3" json:"dealer_visible_card,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "active"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateHandResponse) Reset() {
	*x = CreateHandResponse{}
	mi := &file_pb_blackjack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHandResponse) ProtoMessage() {}

func (x *CreateHandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blackjack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHandResponse.ProtoReflect.Descriptor instead.
func (*CreateHandResponse) Descriptor() ([]byte, []int) {
	return file_pb_blackjack_proto_rawDescGZIP(), []int{3}
}

func (x *CreateHandResponse) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *CreateHandResponse) GetSubHands() []*SubHand {
	if x != nil {
		return x.SubHands
	}
	return nil
}

func (x *CreateHandResponse) GetDealerVisibleCard() *Card {
	if x != nil {
		return x.DealerVisibleCard
	}
	return nil
}

func (x *CreateHandResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PlayerActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandId        string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubHandIndex  int32                  `protobuf:"varint,3,opt,name=sub_hand_index,json=subHandIndex,proto3" json:"sub_hand_index,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // "hit", "stand", "double", "split", "surrender"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerActionRequest) Reset() {
	*x = PlayerActionRequest{}
	mi := &file_pb_blackjack_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActionRequest) ProtoMessage() {}

func (x *PlayerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blackjack_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActionRequest.ProtoReflect.Descriptor instead.
func (*PlayerActionRequest) Descriptor() ([]byte, []int) {
	return file_pb_blackjack_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerActionRequest) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *PlayerActionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerActionRequest) GetSubHandIndex() int32 {
	if x != nil {
		return x.SubHandIndex
	}
	return 0
}

func (x *PlayerActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type PlayerActionResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HandId              string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	SubHands            []*SubHand             `protobuf:"bytes,2,rep,name=sub_hands,json=subHands,proto3" json:"sub_hands,omitempty"`
	DealerCards         []*Card                `protobuf:"bytes,3,rep,name=dealer_cards,json=dealerCards,proto3" json:"dealer_cards,omitempty"`
	Status              string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                                           // "active", "dealer_turn", "settled", "cancelled"
	TotalWinAmountCents int64                  `protobuf:"varint,5,opt,name=total_win_amount_cents,json=totalWinAmountCents,proto3" json:"total_win_amount_cents,omitempty"` // Ganancia final calculada
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlayerActionResponse) Reset() {
	*x = PlayerActionResponse{}
	mi := &file_pb_blackjack_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActionResponse) ProtoMessage() {}

func (x *PlayerActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blackjack_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActionResponse.ProtoReflect.Descriptor instead.
func (*PlayerActionResponse) Descriptor() ([]byte, []int) {
	return file_pb_blackjack_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerActionResponse) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *PlayerActionResponse) GetSubHands() []*SubHand {
	if x != nil {
		return x.SubHands
	}
	return nil
}

func (x *PlayerActionResponse) GetDealerCards() []*Card {
	if x != nil {
		return x.DealerCards
	}
	return nil
}

func (x *PlayerActionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlayerActionResponse) GetTotalWinAmountCents() int64 {
	if x != nil {
		return x.TotalWinAmountCents
	}
	return 0
}

type GetHandStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandId        string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHandStateRequest) Reset() {
	*x = GetHandStateRequest{}
	mi := &file_pb_blackjack_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHandStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHandStateRequest) ProtoMessage() {}

func (x *GetHandStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blackjack_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHandStateRequest.ProtoReflect.Descriptor instead.
func (*GetHandStateRequest) Descriptor() ([]byte, []int) {
	return file_pb_blackjack_proto_rawDescGZIP(), []int{6}
}

func (x *GetHandStateRequest) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *GetHandStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetHandStateResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HandId              string                 `protobuf:"bytes,1,opt,name=hand_id,json=handId,proto3" json:"hand_id,omitempty"`
	SubHands            []*SubHand             `protobuf:"bytes,2,rep,name=sub_hands,json=subHands,proto3" json:"sub_hands,omitempty"`
	DealerCards         []*Card                `protobuf:"bytes,3,rep,name=dealer_cards,json=dealerCards,proto3" json:"dealer_cards,omitempty"`
	Status              string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TotalWinAmountCents int64                  `protobuf:"varint,5,opt,name=total_win_amount_cents,json=totalWinAmountCents,proto3" json:"total_win_amount_cents,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetHandStateResponse) Reset() {
	*x = GetHandStateResponse{}
	mi := &file_pb_blackjack_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHandStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHandStateResponse) ProtoMessage() {}

func (x *GetHandStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blackjack_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHandStateResponse.ProtoReflect.Descriptor instead.
func (*GetHandStateResponse) Descriptor() ([]byte, []int) {
	return file_pb_blackjack_proto_rawDescGZIP(), []int{7}
}

func (x *GetHandStateResponse) GetHandId() string {
	if x != nil {
		return x.HandId
	}
	return ""
}

func (x *GetHandStateResponse) GetSubHands() []*SubHand {
	if x != nil {
		return x.SubHands
	}
	return nil
}

func (x *GetHandStateResponse) GetDealerCards() []*Card {
	if x != nil {
		return x.DealerCards
	}
	return nil
}

func (x *GetHandStateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetHandStateResponse) GetTotalWinAmountCents() int64 {
	if x != nil {
		return x.TotalWinAmountCents
	}
	return 0
}

var File_pb_blackjack_proto protoreflect.FileDescriptor

const file_pb_blackjack_proto_rawDesc = "" +
	"\n" +
	"\x12pb/blackjack.proto\x12\tblackjack\"\\\n" +
	"\x04Card\x12\x12\n" +
	"\x04suit\x18\x01 \x01(\tR\x04suit\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\tR\x04rank\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12\x16\n" +
	"\x06hidden\x18\x04 \x01(\bR\x06hidden\"\xa0\x01\n" +
	"\aSubHand\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12%\n" +
	"\x05cards\x18\x02 \x03(\v2\x0f.blackjack.CardR\x05cards\x12(\n" +
	"\x10bet_amount_cents\x18\x03 \x01(\x03R\x0ebetAmountCents\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\"V\n" +
	"\x11CreateHandRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10bet_amount_cents\x18\x02 \x01(\x03R\x0ebetAmountCents\"\xb7\x01\n" +
	"\x12CreateHandResponse\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\x12/\n" +
	"\tsub_hands\x18\x02 \x03(\v2\x12.blackjack.SubHandR\bsubHands\x12?\n" +
	"\x13dealer_visible_card\x18\x03 \x01(\v2\x0f.blackjack.CardR\x11dealerVisibleCard\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x85\x01\n" +
	"\x13PlayerActionRequest\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x0esub_hand_index\x18\x03 \x01(\x05R\fsubHandIndex\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"\xe1\x01\n" +
	"\x14PlayerActionResponse\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\x12/\n" +
	"\tsub_hands\x18\x02 \x03(\v2\x12.blackjack.SubHandR\bsubHands\x122\n" +
	"\fdealer_cards\x18\x03 \x03(\v2\x0f.blackjack.CardR\vdealerCards\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x123\n" +
	"\x16total_win_amount_cents\x18\x05 \x01(\x03R\x13totalWinAmountCents\"G\n" +
	"\x13GetHandStateRequest\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xe1\x01\n" +
	"\x14GetHandStateResponse\x12\x17\n" +
	"\ahand_id\x18\x01 \x01(\tR\x06handId\x12/\n" +
	"\tsub_hands\x18\x02 \x03(\v2\x12.blackjack.SubHandR\bsubHands\x122\n" +
	"\fdealer_cards\x18\x03 \x03(\v2\x0f.blackjack.CardR\vdealerCards\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x123\n" +
	"\x16total_win_amount_cents\x18\x05 \x01(\x03R\x13totalWinAmountCents2\xff\x01\n" +
	"\x10BlackjackService\x12I\n" +
	"\n" +
	"CreateHand\x12\x1c.blackjack.CreateHandRequest\x1a\x1d.blackjack.CreateHandResponse\x12O\n" +
	"\fPlayerAction\x12\x1e.blackjack.PlayerActionRequest\x1a\x1f.blackjack.PlayerActionResponse\x12O\n" +
	"\fGetHandState\x12\x1e.blackjack.GetHandStateRequest\x1a\x1f.blackjack.GetHandStateResponseB:Z8github.com/ChGSufro/sis-distribuidos-casino/blackjack/pbb\x06proto3"

var (
	file_pb_blackjack_proto_rawDescOnce sync.Once
	file_pb_blackjack_proto_rawDescData []byte
)

func file_pb_blackjack_proto_rawDescGZIP() []byte {
	file_pb_blackjack_proto_rawDescOnce.Do(func() {
		file_pb_blackjack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_blackjack_proto_rawDesc), len(file_pb_blackjack_proto_rawDesc)))
	})
	return file_pb_blackjack_proto_rawDescData
}

var file_pb_blackjack_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_blackjack_proto_goTypes = []any{
	(*Card)(nil),                 // 0: blackjack.Card
	(*SubHand)(nil),              // 1: blackjack.SubHand
	(*CreateHandRequest)(nil),    // 2: blackjack.CreateHandRequest
	(*CreateHandResponse)(nil),   // 3: blackjack.CreateHandResponse
	(*PlayerActionRequest)(nil),  // 4: blackjack.PlayerActionRequest
	(*PlayerActionResponse)(nil), // 5: blackjack.PlayerActionResponse
	(*GetHandStateRequest)(nil),  // 6: blackjack.GetHandStateRequest
	(*GetHandStateResponse)(nil), // 7: blackjack.GetHandStateResponse
}
var file_pb_blackjack_proto_depIdxs = []int32{
	0,  // 0: blackjack.SubHand.cards:type_name -> blackjack.Card
	1,  // 1: blackjack.CreateHandResponse.sub_hands:type_name -> blackjack.SubHand
	0,  // 2: blackjack.CreateHandResponse.dealer_visible_card:type_name -> blackjack.Card
	1,  // 3: blackjack.PlayerActionResponse.sub_hands:type_name -> blackjack.SubHand
	0,  // 4: blackjack.PlayerActionResponse.dealer_cards:type_name -> blackjack.Card
	1,  // 5: blackjack.GetHandStateResponse.sub_hands:type_name -> blackjack.SubHand
	0,  // 6: blackjack.GetHandStateResponse.dealer_cards:type_name -> blackjack.Card
	2,  // 7: blackjack.BlackjackService.CreateHand:input_type -> blackjack.CreateHandRequest
	4,  // 8: blackjack.BlackjackService.PlayerAction:input_type -> blackjack.PlayerActionRequest
	6,  // 9: blackjack.BlackjackService.GetHandState:input_type -> blackjack.GetHandStateRequest
	3,  // 10: blackjack.BlackjackService.CreateHand:output_type -> blackjack.CreateHandResponse
	5,  // 11: blackjack.BlackjackService.PlayerAction:output_type -> blackjack.PlayerActionResponse
	7,  // 12: blackjack.BlackjackService.GetHandState:output_type -> blackjack.GetHandStateResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pb_blackjack_proto_init() }
func file_pb_blackjack_proto_init() {
	if File_pb_blackjack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_blackjack_proto_rawDesc), len(file_pb_blackjack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_blackjack_proto_goTypes,
		DependencyIndexes: file_pb_blackjack_proto_depIdxs,
		MessageInfos:      file_pb_blackjack_proto_msgTypes,
	}.Build()
	File_pb_blackjack_proto = out.File
	file_pb_blackjack_proto_goTypes = nil
	file_pb_blackjack_proto_depIdxs = nil
}
