// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pb/blackjack.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlackjackService_CreateHand_FullMethodName   = "/blackjack.BlackjackService/CreateHand"
	BlackjackService_PlayerAction_FullMethodName = "/blackjack.BlackjackService/PlayerAction"
	BlackjackService_GetHandState_FullMethodName = "/blackjack.BlackjackService/GetHandState"
)

// BlackjackServiceClient is the client API for BlackjackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlackjackServiceClient interface {
	CreateHand(ctx context.Context, in *CreateHandRequest, opts ...grpc.CallOption) (*CreateHandResponse, error)
	PlayerAction(ctx context.Context, in *PlayerActionRequest, opts ...grpc.CallOption) (*PlayerActionResponse, error)
	GetHandState(ctx context.Context, in *GetHandStateRequest, opts ...grpc.CallOption) (*GetHandStateResponse, error)
}

type blackjackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlackjackServiceClient(cc grpc.ClientConnInterface) BlackjackServiceClient {
	return &blackjackServiceClient{cc}
}

func (c *blackjackServiceClient) CreateHand(ctx context.Context, in *CreateHandRequest, opts ...grpc.CallOption) (*CreateHandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHandResponse)
	err := c.cc.Invoke(ctx, BlackjackService_CreateHand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blackjackServiceClient) PlayerAction(ctx context.Context, in *PlayerActionRequest, opts ...grpc.CallOption) (*PlayerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerActionResponse)
	err := c.cc.Invoke(ctx, BlackjackService_PlayerAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blackjackServiceClient) GetHandState(ctx context.Context, in *GetHandStateRequest, opts ...grpc.CallOption) (*GetHandStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHandStateResponse)
	err := c.cc.Invoke(ctx, BlackjackService_GetHandState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlackjackServiceServer is the server API for BlackjackService service.
// All implementations must embed UnimplementedBlackjackServiceServer
// for forward compatibility.
type BlackjackServiceServer interface {
	CreateHand(context.Context, *CreateHandRequest) (*CreateHandResponse, error)
	PlayerAction(context.Context, *PlayerActionRequest) (*PlayerActionResponse, error)
	GetHandState(context.Context, *GetHandStateRequest) (*GetHandStateResponse, error)
	mustEmbedUnimplementedBlackjackServiceServer()
}

// UnimplementedBlackjackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlackjackServiceServer struct{}

func (UnimplementedBlackjackServiceServer) CreateHand(context.Context, *CreateHandRequest) (*CreateHandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHand not implemented")
}
func (UnimplementedBlackjackServiceServer) PlayerAction(context.Context, *PlayerActionRequest) (*PlayerActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayerAction not implemented")
}
func (UnimplementedBlackjackServiceServer) GetHandState(context.Context, *GetHandStateRequest) (*GetHandStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHandState not implemented")
}
func (UnimplementedBlackjackServiceServer) mustEmbedUnimplementedBlackjackServiceServer() {}
func (UnimplementedBlackjackServiceServer) testEmbeddedByValue()                          {}

// UnsafeBlackjackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlackjackServiceServer will
// result in compilation errors.
type UnsafeBlackjackServiceServer interface {
	mustEmbedUnimplementedBlackjackServiceServer()
}

func RegisterBlackjackServiceServer(s grpc.ServiceRegistrar, srv BlackjackServiceServer) {
	// If the following call panics, it indicates UnimplementedBlackjackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlackjackService_ServiceDesc, srv)
}

func _BlackjackService_CreateHand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlackjackServiceServer).CreateHand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlackjackService_CreateHand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlackjackServiceServer).CreateHand(ctx, req.(*CreateHandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlackjackService_PlayerAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlackjackServiceServer).PlayerAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlackjackService_PlayerAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlackjackServiceServer).PlayerAction(ctx, req.(*PlayerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlackjackService_GetHandState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHandStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlackjackServiceServer).GetHandState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlackjackService_GetHandState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlackjackServiceServer).GetHandState(ctx, req.(*GetHandStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlackjackService_ServiceDesc is the grpc.ServiceDesc for BlackjackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlackjackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blackjack.BlackjackService",
	HandlerType: (*BlackjackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHand",
			Handler:    _BlackjackService_CreateHand_Handler,
		},
		{
			MethodName: "PlayerAction",
			Handler:    _BlackjackService_PlayerAction_Handler,
		},
		{
			MethodName: "GetHandState",
			Handler:    _BlackjackService_GetHandState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/blackjack.proto",
}
