// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: pb/history.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Evento de juego registrado en el historial del jugador
type GameEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`         // UUID del evento
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`            // Identificador del jugador
	GameType  string                 `protobuf:"bytes,3,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`      // "blackjack" | "poker"
	GameRefId string                 `protobuf:"bytes,4,opt,name=game_ref_id,json=gameRefId,proto3" json:"game_ref_id,omitempty"` // ObjectId hex de la mano o mesa
	Action    string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`                          // "hand_result" | "bet_placed" | "hand_cancelled" |
	// "table_result" | "player_buyin" | "player_payout" |
	// "player_eliminated"
	Details       string `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"`     // JSON con el contenido variable segun la accion
	Timestamp     string `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Formato ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_pb_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_pb_history_proto_rawDescGZIP(), []int{0}
}

func (x *GameEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GameEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GameEvent) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *GameEvent) GetGameRefId() string {
	if x != nil {
		return x.GameRefId
	}
	return ""
}

func (x *GameEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GameEvent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *GameEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Registro de un evento de juego
type RecordGameEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *GameEvent             `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordGameEventRequest) Reset() {
	*x = RecordGameEventRequest{}
	mi := &file_pb_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordGameEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordGameEventRequest) ProtoMessage() {}

func (x *RecordGameEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordGameEventRequest.ProtoReflect.Descriptor instead.
func (*RecordGameEventRequest) Descriptor() ([]byte, []int) {
	return file_pb_history_proto_rawDescGZIP(), []int{1}
}

func (x *RecordGameEventRequest) GetEvent() *GameEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type RecordGameEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                           // "recorded"
	RecordedAt    string                 `protobuf:"bytes,3,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"` // Formato ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordGameEventResponse) Reset() {
	*x = RecordGameEventResponse{}
	mi := &file_pb_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordGameEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordGameEventResponse) ProtoMessage() {}

func (x *RecordGameEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordGameEventResponse.ProtoReflect.Descriptor instead.
func (*RecordGameEventResponse) Descriptor() ([]byte, []int) {
	return file_pb_history_proto_rawDescGZIP(), []int{2}
}

func (x *RecordGameEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RecordGameEventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecordGameEventResponse) GetRecordedAt() string {
	if x != nil {
		return x.RecordedAt
	}
	return ""
}

// Consulta del historial de un jugador
type GetPlayerHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameType      string                 `protobuf:"bytes,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"` // Vacio = todos los juegos
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerHistoryRequest) Reset() {
	*x = GetPlayerHistoryRequest{}
	mi := &file_pb_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerHistoryRequest) ProtoMessage() {}

func (x *GetPlayerHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pb_history_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPlayerHistoryRequest) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *GetPlayerHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPlayerHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetPlayerHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*GameEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerHistoryResponse) Reset() {
	*x = GetPlayerHistoryResponse{}
	mi := &file_pb_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerHistoryResponse) ProtoMessage() {}

func (x *GetPlayerHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerHistoryResponse) Descriptor() ([]byte, []int) {
	return file_pb_history_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlayerHistoryResponse) GetEvents() []*GameEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetPlayerHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_pb_history_proto protoreflect.FileDescriptor

const file_pb_history_proto_rawDesc = "" +
	"\n" +
	"\x10pb/history.proto\x12\ahistory\"\xcc\x01\n" +
	"\tGameEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tgame_type\x18\x03 \x01(\tR\bgameType\x12\x1e\n" +
	"\vgame_ref_id\x18\x04 \x01(\tR\tgameRefId\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x18\n" +
	"\adetails\x18\x06 \x01(\tR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\"B\n" +
	"\x16RecordGameEventRequest\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.history.GameEventR\x05event\"m\n" +
	"\x17RecordGameEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vrecorded_at\x18\x03 \x01(\tR\n" +
	"recordedAt\"}\n" +
	"\x17GetPlayerHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tgame_type\x18\x02 \x01(\tR\bgameType\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"g\n" +
	"\x18GetPlayerHistoryResponse\x12*\n" +
	"\x06events\x18\x01 \x03(\v2\x12.history.GameEventR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\xbf\x01\n" +
	"\x0eHistoryService\x12T\n" +
	"\x0fRecordGameEvent\x12\x1f.history.RecordGameEventRequest\x1a .history.RecordGameEventResponse\x12W\n" +
	"\x10GetPlayerHistory\x12 .history.GetPlayerHistoryRequest\x1a!.history.GetPlayerHistoryResponseB8Z6github.com/ChGSufro/sis-distribuidos-casino/history/pbb\x06proto3"

var (
	file_pb_history_proto_rawDescOnce sync.Once
	file_pb_history_proto_rawDescData []byte
)

func file_pb_history_proto_rawDescGZIP() []byte {
	file_pb_history_proto_rawDescOnce.Do(func() {
		file_pb_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_history_proto_rawDesc), len(file_pb_history_proto_rawDesc)))
	})
	return file_pb_history_proto_rawDescData
}

var file_pb_history_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_history_proto_goTypes = []any{
	(*GameEvent)(nil),                // 0: history.GameEvent
	(*RecordGameEventRequest)(nil),   // 1: history.RecordGameEventRequest
	(*RecordGameEventResponse)(nil),  // 2: history.RecordGameEventResponse
	(*GetPlayerHistoryRequest)(nil),  // 3: history.GetPlayerHistoryRequest
	(*GetPlayerHistoryResponse)(nil), // 4: history.GetPlayerHistoryResponse
}
var file_pb_history_proto_depIdxs = []int32{
	0, // 0: history.RecordGameEventRequest.event:type_name -> history.GameEvent
	0, // 1: history.GetPlayerHistoryResponse.events:type_name -> history.GameEvent
	1, // 2: history.HistoryService.RecordGameEvent:input_type -> history.RecordGameEventRequest
	3, // 3: history.HistoryService.GetPlayerHistory:input_type -> history.GetPlayerHistoryRequest
	2, // 4: history.HistoryService.RecordGameEvent:output_type -> history.RecordGameEventResponse
	4, // 5: history.HistoryService.GetPlayerHistory:output_type -> history.GetPlayerHistoryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_history_proto_init() }
func file_pb_history_proto_init() {
	if File_pb_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_history_proto_rawDesc), len(file_pb_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_history_proto_goTypes,
		DependencyIndexes: file_pb_history_proto_depIdxs,
		MessageInfos:      file_pb_history_proto_msgTypes,
	}.Build()
	File_pb_history_proto = out.File
	file_pb_history_proto_goTypes = nil
	file_pb_history_proto_depIdxs = nil
}
