// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pb/wallet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Inicialización de billetera para nuevo usuario
type InitWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitWalletRequest) Reset() {
	*x = InitWalletRequest{}
	mi := &file_pb_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitWalletRequest) ProtoMessage() {}

func (x *InitWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitWalletRequest.ProtoReflect.Descriptor instead.
func (*InitWalletRequest) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *InitWalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type InitWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	BalanceCents  int64                  `protobuf:"varint,2,opt,name=balance_cents,json=balanceCents,proto3" json:"balance_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitWalletResponse) Reset() {
	*x = InitWalletResponse{}
	mi := &file_pb_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitWalletResponse) ProtoMessage() {}

func (x *InitWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitWalletResponse.ProtoReflect.Descriptor instead.
func (*InitWalletResponse) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *InitWalletResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *InitWalletResponse) GetBalanceCents() int64 {
	if x != nil {
		return x.BalanceCents
	}
	return 0
}

// Consulta de saldo
type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_pb_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BalanceCents  int64                  `protobuf:"varint,2,opt,name=balance_cents,json=balanceCents,proto3" json:"balance_cents,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Formato ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_pb_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceResponse) GetBalanceCents() int64 {
	if x != nil {
		return x.BalanceCents
	}
	return 0
}

func (x *GetBalanceResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Depósito de fondos
type DepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_pb_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *DepositRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DepositRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

type DepositResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	NewBalanceCents int64                  `protobuf:"varint,2,opt,name=new_balance_cents,json=newBalanceCents,proto3" json:"new_balance_cents,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DepositResponse) Reset() {
	*x = DepositResponse{}
	mi := &file_pb_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositResponse) ProtoMessage() {}

func (x *DepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositResponse.ProtoReflect.Descriptor instead.
func (*DepositResponse) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *DepositResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DepositResponse) GetNewBalanceCents() int64 {
	if x != nil {
		return x.NewBalanceCents
	}
	return 0
}

// Reserva de fondos para iniciar o continuar apuestas
type HoldRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents    int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	GameType       string                 `protobuf:"bytes,3,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`      // "blackjack" | "poker"
	GameRefId      string                 `protobuf:"bytes,4,opt,name=game_ref_id,json=gameRefId,proto3" json:"game_ref_id,omitempty"` // ObjectId hex de la mano o mesa
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HoldRequest) Reset() {
	*x = HoldRequest{}
	mi := &file_pb_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldRequest) ProtoMessage() {}

func (x *HoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldRequest.ProtoReflect.Descriptor instead.
func (*HoldRequest) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *HoldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HoldRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *HoldRequest) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *HoldRequest) GetGameRefId() string {
	if x != nil {
		return x.GameRefId
	}
	return ""
}

func (x *HoldRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type HoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "active"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldResponse) Reset() {
	*x = HoldResponse{}
	mi := &file_pb_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldResponse) ProtoMessage() {}

func (x *HoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldResponse.ProtoReflect.Descriptor instead.
func (*HoldResponse) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *HoldResponse) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

func (x *HoldResponse) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *HoldResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Liquidación de reserva tras resolver la partida
type SettleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HoldId         string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	WinAmountCents int64                  `protobuf:"varint,2,opt,name=win_amount_cents,json=winAmountCents,proto3" json:"win_amount_cents,omitempty"` // Monto ganado (0 si perdió todo)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SettleRequest) Reset() {
	*x = SettleRequest{}
	mi := &file_pb_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRequest) ProtoMessage() {}

func (x *SettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRequest.ProtoReflect.Descriptor instead.
func (*SettleRequest) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *SettleRequest) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

func (x *SettleRequest) GetWinAmountCents() int64 {
	if x != nil {
		return x.WinAmountCents
	}
	return 0
}

type SettleResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HoldId          string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "settled"
	TransactionId   string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	NewBalanceCents int64                  `protobuf:"varint,4,opt,name=new_balance_cents,json=newBalanceCents,proto3" json:"new_balance_cents,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SettleResponse) Reset() {
	*x = SettleResponse{}
	mi := &file_pb_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleResponse) ProtoMessage() {}

func (x *SettleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleResponse.ProtoReflect.Descriptor instead.
func (*SettleResponse) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *SettleResponse) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

func (x *SettleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SettleResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *SettleResponse) GetNewBalanceCents() int64 {
	if x != nil {
		return x.NewBalanceCents
	}
	return 0
}

// Liberación/cancelación de reserva devolviendo el saldo original
type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_pb_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseRequest) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

type ReleaseResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HoldId          string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "released"
	TransactionId   string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	NewBalanceCents int64                  `protobuf:"varint,4,opt,name=new_balance_cents,json=newBalanceCents,proto3" json:"new_balance_cents,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_pb_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseResponse) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

func (x *ReleaseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReleaseResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ReleaseResponse) GetNewBalanceCents() int64 {
	if x != nil {
		return x.NewBalanceCents
	}
	return 0
}

var File_pb_wallet_proto protoreflect.FileDescriptor

const file_pb_wallet_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/wallet.proto\x12\x06wallet\",\n" +
	"\x11InitWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"V\n" +
	"\x12InitWalletResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12#\n" +
	"\rbalance_cents\x18\x02 \x01(\x03R\fbalanceCents\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"q\n" +
	"\x12GetBalanceResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbalance_cents\x18\x02 \x01(\x03R\fbalanceCents\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\"L\n" +
	"\x0eDepositRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\"d\n" +
	"\x0fDepositResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12*\n" +
	"\x11new_balance_cents\x18\x02 \x01(\x03R\x0fnewBalanceCents\"\xaf\x01\n" +
	"\vHoldRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12\x1b\n" +
	"\tgame_type\x18\x03 \x01(\tR\bgameType\x12\x1e\n" +
	"\vgame_ref_id\x18\x04 \x01(\tR\tgameRefId\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"b\n" +
	"\fHoldResponse\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"R\n" +
	"\rSettleRequest\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\x12(\n" +
	"\x10win_amount_cents\x18\x02 \x01(\x03R\x0ewinAmountCents\"\x94\x01\n" +
	"\x0eSettleResponse\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12*\n" +
	"\x11new_balance_cents\x18\x04 \x01(\x03R\x0fnewBalanceCents\")\n" +
	"\x0eReleaseRequest\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\"\x95\x01\n" +
	"\x0fReleaseResponse\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12*\n" +
	"\x11new_balance_cents\x18\x04 \x01(\x03R\x0fnewBalanceCents2\xfd\x02\n" +
	"\rWalletService\x12C\n" +
	"\n" +
	"InitWallet\x12\x19.wallet.InitWalletRequest\x1a\x1a.wallet.InitWalletResponse\x12C\n" +
	"\n" +
	"GetBalance\x12\x19.wallet.GetBalanceRequest\x1a\x1a.wallet.GetBalanceResponse\x12:\n" +
	"\aDeposit\x12\x16.wallet.DepositRequest\x1a\x17.wallet.DepositResponse\x121\n" +
	"\x04Hold\x12\x13.wallet.HoldRequest\x1a\x14.wallet.HoldResponse\x127\n" +
	"\x06Settle\x12\x15.wallet.SettleRequest\x1a\x16.wallet.SettleResponse\x12:\n" +
	"\aRelease\x12\x16.wallet.ReleaseRequest\x1a\x17.wallet.ReleaseResponseB7Z5github.com/ChGSufro/sis-distribuidos-casino/wallet/pbb\x06proto3"

var (
	file_pb_wallet_proto_rawDescOnce sync.Once
	file_pb_wallet_proto_rawDescData []byte
)

func file_pb_wallet_proto_rawDescGZIP() []byte {
	file_pb_wallet_proto_rawDescOnce.Do(func() {
		file_pb_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_wallet_proto_rawDesc), len(file_pb_wallet_proto_rawDesc)))
	})
	return file_pb_wallet_proto_rawDescData
}

var file_pb_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pb_wallet_proto_goTypes = []any{
	(*InitWalletRequest)(nil),  // 0: wallet.InitWalletRequest
	(*InitWalletResponse)(nil), // 1: wallet.InitWalletResponse
	(*GetBalanceRequest)(nil),  // 2: wallet.GetBalanceRequest
	(*GetBalanceResponse)(nil), // 3: wallet.GetBalanceResponse
	(*DepositRequest)(nil),     // 4: wallet.DepositRequest
	(*DepositResponse)(nil),    // 5: wallet.DepositResponse
	(*HoldRequest)(nil),        // 6: wallet.HoldRequest
	(*HoldResponse)(nil),       // 7: wallet.HoldResponse
	(*SettleRequest)(nil),      // 8: wallet.SettleRequest
	(*SettleResponse)(nil),     // 9: wallet.SettleResponse
	(*ReleaseRequest)(nil),     // 10: wallet.ReleaseRequest
	(*ReleaseResponse)(nil),    // 11: wallet.ReleaseResponse
}
var file_pb_wallet_proto_depIdxs = []int32{
	0,  // 0: wallet.WalletService.InitWallet:input_type -> wallet.InitWalletRequest
	2,  // 1: wallet.WalletService.GetBalance:input_type -> wallet.GetBalanceRequest
	4,  // 2: wallet.WalletService.Deposit:input_type -> wallet.DepositRequest
	6,  // 3: wallet.WalletService.Hold:input_type -> wallet.HoldRequest
	8,  // 4: wallet.WalletService.Settle:input_type -> wallet.SettleRequest
	10, // 5: wallet.WalletService.Release:input_type -> wallet.ReleaseRequest
	1,  // 6: wallet.WalletService.InitWallet:output_type -> wallet.InitWalletResponse
	3,  // 7: wallet.WalletService.GetBalance:output_type -> wallet.GetBalanceResponse
	5,  // 8: wallet.WalletService.Deposit:output_type -> wallet.DepositResponse
	7,  // 9: wallet.WalletService.Hold:output_type -> wallet.HoldResponse
	9,  // 10: wallet.WalletService.Settle:output_type -> wallet.SettleResponse
	11, // 11: wallet.WalletService.Release:output_type -> wallet.ReleaseResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pb_wallet_proto_init() }
func file_pb_wallet_proto_init() {
	if File_pb_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_wallet_proto_rawDesc), len(file_pb_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_wallet_proto_goTypes,
		DependencyIndexes: file_pb_wallet_proto_depIdxs,
		MessageInfos:      file_pb_wallet_proto_msgTypes,
	}.Build()
	File_pb_wallet_proto = out.File
	file_pb_wallet_proto_goTypes = nil
	file_pb_wallet_proto_depIdxs = nil
}
