// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pb/poker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Carta del mazo. En Poker no lleva valor numerico:
// el valor se deriva de la posicion dentro de la mano.
type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suit          string                 `protobuf:"bytes,1,opt,name=suit,proto3" json:"suit,omitempty"` // "H" (Corazones), "D" (Diamantes), "C" (Treboles), "S" (Picas)
	Rank          string                 `protobuf:"bytes,2,opt,name=rank,proto3" json:"rank,omitempty"` // "2".."10", "J", "Q", "K", "A"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_pb_poker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetSuit() string {
	if x != nil {
		return x.Suit
	}
	return ""
}

func (x *Card) GetRank() string {
	if x != nil {
		return x.Rank
	}
	return ""
}

// Mesa de poker. Entidad central del servicio.
type Table struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TableId         string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"` // ObjectId hex
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SmallBlindCents int64                  `protobuf:"varint,3,opt,name=small_blind_cents,json=smallBlindCents,proto3" json:"small_blind_cents,omitempty"`
	BigBlindCents   int64                  `protobuf:"varint,4,opt,name=big_blind_cents,json=bigBlindCents,proto3" json:"big_blind_cents,omitempty"`
	MaxPlayers      int32                  `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`             // 2..10
	CurrentPlayers  int32                  `protobuf:"varint,6,opt,name=current_players,json=currentPlayers,proto3" json:"current_players,omitempty"` // jugadores sentados actualmente
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                                        // "waiting", "active", "paused", "closed"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_pb_poker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{1}
}

func (x *Table) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetSmallBlindCents() int64 {
	if x != nil {
		return x.SmallBlindCents
	}
	return 0
}

func (x *Table) GetBigBlindCents() int64 {
	if x != nil {
		return x.BigBlindCents
	}
	return 0
}

func (x *Table) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *Table) GetCurrentPlayers() int32 {
	if x != nil {
		return x.CurrentPlayers
	}
	return 0
}

func (x *Table) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Jugador sentado en la mesa, sin informacion privada
type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatPosition  int32                  `protobuf:"varint,1,opt,name=seat_position,json=seatPosition,proto3" json:"seat_position,omitempty"` // 1..max_players
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StackCents    int64                  `protobuf:"varint,3,opt,name=stack_cents,json=stackCents,proto3" json:"stack_cents,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "active", "folded", "all_in", "sitting_out"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_pb_poker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{2}
}

func (x *Seat) GetSeatPosition() int32 {
	if x != nil {
		return x.SeatPosition
	}
	return 0
}

func (x *Seat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Seat) GetStackCents() int64 {
	if x != nil {
		return x.StackCents
	}
	return 0
}

func (x *Seat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Estado de un jugador dentro de la ronda en curso
type PlayerState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SeatPosition         int32                  `protobuf:"varint,2,opt,name=seat_position,json=seatPosition,proto3" json:"seat_position,omitempty"`
	StackCents           int64                  `protobuf:"varint,3,opt,name=stack_cents,json=stackCents,proto3" json:"stack_cents,omitempty"`
	TotalBetInRoundCents int64                  `protobuf:"varint,4,opt,name=total_bet_in_round_cents,json=totalBetInRoundCents,proto3" json:"total_bet_in_round_cents,omitempty"`
	Status               string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "active", "folded", "all_in"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_pb_poker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerState) GetSeatPosition() int32 {
	if x != nil {
		return x.SeatPosition
	}
	return 0
}

func (x *PlayerState) GetStackCents() int64 {
	if x != nil {
		return x.StackCents
	}
	return 0
}

func (x *PlayerState) GetTotalBetInRoundCents() int64 {
	if x != nil {
		return x.TotalBetInRoundCents
	}
	return 0
}

func (x *PlayerState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Ganador de un bote al cerrar la ronda
type Winner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PotType       string                 `protobuf:"bytes,2,opt,name=pot_type,json=potType,proto3" json:"pot_type,omitempty"` // "main", "side"
	AmountCents   int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Winner) Reset() {
	*x = Winner{}
	mi := &file_pb_poker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Winner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Winner) ProtoMessage() {}

func (x *Winner) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Winner.ProtoReflect.Descriptor instead.
func (*Winner) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{4}
}

func (x *Winner) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Winner) GetPotType() string {
	if x != nil {
		return x.PotType
	}
	return ""
}

func (x *Winner) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

// Ronda en curso. your_hole_cards contiene solo las cartas
// privadas del usuario que consulta; las demas no se envian
// hasta el showdown.
type RoundState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoundId         string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Stage           string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"` // "waiting", "preflop", "flop", "turn", "river", "settled"
	CommunityCards  []*Card                `protobuf:"bytes,3,rep,name=community_cards,json=communityCards,proto3" json:"community_cards,omitempty"`
	YourHoleCards   []*Card                `protobuf:"bytes,4,rep,name=your_hole_cards,json=yourHoleCards,proto3" json:"your_hole_cards,omitempty"`
	PotSizeCents    int64                  `protobuf:"varint,5,opt,name=pot_size_cents,json=potSizeCents,proto3" json:"pot_size_cents,omitempty"`
	CurrentBetCents int64                  `protobuf:"varint,6,opt,name=current_bet_cents,json=currentBetCents,proto3" json:"current_bet_cents,omitempty"`
	CurrentTurn     int32                  `protobuf:"varint,7,opt,name=current_turn,json=currentTurn,proto3" json:"current_turn,omitempty"`        // seat_position del siguiente en actuar
	TurnExpiresAt   string                 `protobuf:"bytes,8,opt,name=turn_expires_at,json=turnExpiresAt,proto3" json:"turn_expires_at,omitempty"` // ISO 8601
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoundState) Reset() {
	*x = RoundState{}
	mi := &file_pb_poker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundState) ProtoMessage() {}

func (x *RoundState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundState.ProtoReflect.Descriptor instead.
func (*RoundState) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{5}
}

func (x *RoundState) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *RoundState) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *RoundState) GetCommunityCards() []*Card {
	if x != nil {
		return x.CommunityCards
	}
	return nil
}

func (x *RoundState) GetYourHoleCards() []*Card {
	if x != nil {
		return x.YourHoleCards
	}
	return nil
}

func (x *RoundState) GetPotSizeCents() int64 {
	if x != nil {
		return x.PotSizeCents
	}
	return 0
}

func (x *RoundState) GetCurrentBetCents() int64 {
	if x != nil {
		return x.CurrentBetCents
	}
	return 0
}

func (x *RoundState) GetCurrentTurn() int32 {
	if x != nil {
		return x.CurrentTurn
	}
	return 0
}

func (x *RoundState) GetTurnExpiresAt() string {
	if x != nil {
		return x.TurnExpiresAt
	}
	return ""
}

// Difusion del estado de la mesa a todos los jugadores sentados
type TableUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoundId         string                 `protobuf:"bytes,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Stage           string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	CurrentTurn     int32                  `protobuf:"varint,3,opt,name=current_turn,json=currentTurn,proto3" json:"current_turn,omitempty"`
	CurrentBetCents int64                  `protobuf:"varint,4,opt,name=current_bet_cents,json=currentBetCents,proto3" json:"current_bet_cents,omitempty"`
	PotSizeCents    int64                  `protobuf:"varint,5,opt,name=pot_size_cents,json=potSizeCents,proto3" json:"pot_size_cents,omitempty"`
	CommunityCards  []*Card                `protobuf:"bytes,6,rep,name=community_cards,json=communityCards,proto3" json:"community_cards,omitempty"`
	Players         []*PlayerState         `protobuf:"bytes,7,rep,name=players,proto3" json:"players,omitempty"`
	TurnExpiresAt   string                 `protobuf:"bytes,8,opt,name=turn_expires_at,json=turnExpiresAt,proto3" json:"turn_expires_at,omitempty"` // ISO 8601
	Winners         []*Winner              `protobuf:"bytes,9,rep,name=winners,proto3" json:"winners,omitempty"`                                    // vacio mientras stage != "settled"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TableUpdate) Reset() {
	*x = TableUpdate{}
	mi := &file_pb_poker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableUpdate) ProtoMessage() {}

func (x *TableUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableUpdate.ProtoReflect.Descriptor instead.
func (*TableUpdate) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{6}
}

func (x *TableUpdate) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *TableUpdate) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *TableUpdate) GetCurrentTurn() int32 {
	if x != nil {
		return x.CurrentTurn
	}
	return 0
}

func (x *TableUpdate) GetCurrentBetCents() int64 {
	if x != nil {
		return x.CurrentBetCents
	}
	return 0
}

func (x *TableUpdate) GetPotSizeCents() int64 {
	if x != nil {
		return x.PotSizeCents
	}
	return 0
}

func (x *TableUpdate) GetCommunityCards() []*Card {
	if x != nil {
		return x.CommunityCards
	}
	return nil
}

func (x *TableUpdate) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *TableUpdate) GetTurnExpiresAt() string {
	if x != nil {
		return x.TurnExpiresAt
	}
	return ""
}

func (x *TableUpdate) GetWinners() []*Winner {
	if x != nil {
		return x.Winners
	}
	return nil
}

// Listado de mesas, opcionalmente filtrado por estado
type ListTablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  string                 `protobuf:"bytes,1,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // "waiting", "active", o vacio = todas
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTablesRequest) Reset() {
	*x = ListTablesRequest{}
	mi := &file_pb_poker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTablesRequest) ProtoMessage() {}

func (x *ListTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTablesRequest.ProtoReflect.Descriptor instead.
func (*ListTablesRequest) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{7}
}

func (x *ListTablesRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListTablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*Table               `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTablesResponse) Reset() {
	*x = ListTablesResponse{}
	mi := &file_pb_poker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTablesResponse) ProtoMessage() {}

func (x *ListTablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTablesResponse.ProtoReflect.Descriptor instead.
func (*ListTablesResponse) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{8}
}

func (x *ListTablesResponse) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

// Creacion de una mesa por parte de un usuario
type CreateTableRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // usuario que crea la mesa
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SmallBlindCents int64                  `protobuf:"varint,3,opt,name=small_blind_cents,json=smallBlindCents,proto3" json:"small_blind_cents,omitempty"`
	BigBlindCents   int64                  `protobuf:"varint,4,opt,name=big_blind_cents,json=bigBlindCents,proto3" json:"big_blind_cents,omitempty"`
	MaxPlayers      int32                  `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"` // 2..10
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTableRequest) Reset() {
	*x = CreateTableRequest{}
	mi := &file_pb_poker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableRequest) ProtoMessage() {}

func (x *CreateTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableRequest.ProtoReflect.Descriptor instead.
func (*CreateTableRequest) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTableRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTableRequest) GetSmallBlindCents() int64 {
	if x != nil {
		return x.SmallBlindCents
	}
	return 0
}

func (x *CreateTableRequest) GetBigBlindCents() int64 {
	if x != nil {
		return x.BigBlindCents
	}
	return 0
}

func (x *CreateTableRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type CreateTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *Table                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"` // recien creada: current_players = 0, status = "waiting"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTableResponse) Reset() {
	*x = CreateTableResponse{}
	mi := &file_pb_poker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableResponse) ProtoMessage() {}

func (x *CreateTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableResponse.ProtoReflect.Descriptor instead.
func (*CreateTableResponse) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTableResponse) GetTable() *Table {
	if x != nil {
		return x.Table
	}
	return nil
}

// Compra de fichas y asignacion de asiento.
// El buy-in se reserva internamente via Wallet.Hold.
type JoinTableRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TableId          string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BuyInAmountCents int64                  `protobuf:"varint,3,opt,name=buy_in_amount_cents,json=buyInAmountCents,proto3" json:"buy_in_amount_cents,omitempty"` // > 0
	PreferredSeat    int32                  `protobuf:"varint,4,opt,name=preferred_seat,json=preferredSeat,proto3" json:"preferred_seat,omitempty"`              // 0 = asignar el primer asiento libre
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JoinTableRequest) Reset() {
	*x = JoinTableRequest{}
	mi := &file_pb_poker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTableRequest) ProtoMessage() {}

func (x *JoinTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTableRequest.ProtoReflect.Descriptor instead.
func (*JoinTableRequest) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{11}
}

func (x *JoinTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *JoinTableRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinTableRequest) GetBuyInAmountCents() int64 {
	if x != nil {
		return x.BuyInAmountCents
	}
	return 0
}

func (x *JoinTableRequest) GetPreferredSeat() int32 {
	if x != nil {
		return x.PreferredSeat
	}
	return 0
}

type JoinTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	SeatPosition  int32                  `protobuf:"varint,2,opt,name=seat_position,json=seatPosition,proto3" json:"seat_position,omitempty"`
	StackCents    int64                  `protobuf:"varint,3,opt,name=stack_cents,json=stackCents,proto3" json:"stack_cents,omitempty"` // fichas acreditadas en mesa
	HoldId        string                 `protobuf:"bytes,4,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`              // referencia a la reserva en Wallet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTableResponse) Reset() {
	*x = JoinTableResponse{}
	mi := &file_pb_poker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTableResponse) ProtoMessage() {}

func (x *JoinTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTableResponse.ProtoReflect.Descriptor instead.
func (*JoinTableResponse) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{12}
}

func (x *JoinTableResponse) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *JoinTableResponse) GetSeatPosition() int32 {
	if x != nil {
		return x.SeatPosition
	}
	return 0
}

func (x *JoinTableResponse) GetStackCents() int64 {
	if x != nil {
		return x.StackCents
	}
	return 0
}

func (x *JoinTableResponse) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

// Salida de la mesa. El stack se liquida via Wallet.Settle.
type LeaveTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveTableRequest) Reset() {
	*x = LeaveTableRequest{}
	mi := &file_pb_poker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveTableRequest) ProtoMessage() {}

func (x *LeaveTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveTableRequest.ProtoReflect.Descriptor instead.
func (*LeaveTableRequest) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{13}
}

func (x *LeaveTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *LeaveTableRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveTableResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TableId            string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	FinalStackCents    int64                  `protobuf:"varint,2,opt,name=final_stack_cents,json=finalStackCents,proto3" json:"final_stack_cents,omitempty"`          // fichas al momento de salir
	SettledAmountCents int64                  `protobuf:"varint,3,opt,name=settled_amount_cents,json=settledAmountCents,proto3" json:"settled_amount_cents,omitempty"` // monto devuelto a la billetera
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LeaveTableResponse) Reset() {
	*x = LeaveTableResponse{}
	mi := &file_pb_poker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveTableResponse) ProtoMessage() {}

func (x *LeaveTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveTableResponse.ProtoReflect.Descriptor instead.
func (*LeaveTableResponse) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{14}
}

func (x *LeaveTableResponse) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *LeaveTableResponse) GetFinalStackCents() int64 {
	if x != nil {
		return x.FinalStackCents
	}
	return 0
}

func (x *LeaveTableResponse) GetSettledAmountCents() int64 {
	if x != nil {
		return x.SettledAmountCents
	}
	return 0
}

// Accion del jugador en su turno de la ronda en curso
type PlayerActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	RoundId       string                 `protobuf:"bytes,2,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`                               // "fold", "check", "call", "raise", "all-in"
	AmountCents   int64                  `protobuf:"varint,5,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"` // monto del raise, requerido solo para "raise"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerActionRequest) Reset() {
	*x = PlayerActionRequest{}
	mi := &file_pb_poker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActionRequest) ProtoMessage() {}

func (x *PlayerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActionRequest.ProtoReflect.Descriptor instead.
func (*PlayerActionRequest) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerActionRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *PlayerActionRequest) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *PlayerActionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PlayerActionRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

type PlayerActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        *TableUpdate           `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"` // se difunde a todos los jugadores de la mesa
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerActionResponse) Reset() {
	*x = PlayerActionResponse{}
	mi := &file_pb_poker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActionResponse) ProtoMessage() {}

func (x *PlayerActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActionResponse.ProtoReflect.Descriptor instead.
func (*PlayerActionResponse) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{16}
}

func (x *PlayerActionResponse) GetUpdate() *TableUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

// Consulta del estado completo de una mesa.
// user_id determina que cartas privadas se incluyen.
type GetTableStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableStateRequest) Reset() {
	*x = GetTableStateRequest{}
	mi := &file_pb_poker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableStateRequest) ProtoMessage() {}

func (x *GetTableStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableStateRequest.ProtoReflect.Descriptor instead.
func (*GetTableStateRequest) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{17}
}

func (x *GetTableStateRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *GetTableStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTableStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *Table                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Seats         []*Seat                `protobuf:"bytes,2,rep,name=seats,proto3" json:"seats,omitempty"`
	CurrentRound  *RoundState            `protobuf:"bytes,3,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"` // vacio si la mesa no tiene ronda en curso
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableStateResponse) Reset() {
	*x = GetTableStateResponse{}
	mi := &file_pb_poker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableStateResponse) ProtoMessage() {}

func (x *GetTableStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_poker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableStateResponse.ProtoReflect.Descriptor instead.
func (*GetTableStateResponse) Descriptor() ([]byte, []int) {
	return file_pb_poker_proto_rawDescGZIP(), []int{18}
}

func (x *GetTableStateResponse) GetTable() *Table {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *GetTableStateResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *GetTableStateResponse) GetCurrentRound() *RoundState {
	if x != nil {
		return x.CurrentRound
	}
	return nil
}

var File_pb_poker_proto protoreflect.FileDescriptor

const file_pb_poker_proto_rawDesc = "" +
	"\n" +
	"\x0epb/poker.proto\x12\x05poker\".\n" +
	"\x04Card\x12\x12\n" +
	"\x04suit\x18\x01 \x01(\tR\x04suit\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\tR\x04rank\"\xec\x01\n" +
	"\x05Table\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x11small_blind_cents\x18\x03 \x01(\x03R\x0fsmallBlindCents\x12&\n" +
	"\x0fbig_blind_cents\x18\x04 \x01(\x03R\rbigBlindCents\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\x05R\n" +
	"maxPlayers\x12'\n" +
	"\x0fcurrent_players\x18\x06 \x01(\x05R\x0ecurrentPlayers\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"}\n" +
	"\x04Seat\x12#\n" +
	"\rseat_position\x18\x01 \x01(\x05R\fseatPosition\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vstack_cents\x18\x03 \x01(\x03R\n" +
	"stackCents\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xbc\x01\n" +
	"\vPlayerState\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rseat_position\x18\x02 \x01(\x05R\fseatPosition\x12\x1f\n" +
	"\vstack_cents\x18\x03 \x01(\x03R\n" +
	"stackCents\x126\n" +
	"\x18total_bet_in_round_cents\x18\x04 \x01(\x03R\x14totalBetInRoundCents\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"_\n" +
	"\x06Winner\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bpot_type\x18\x02 \x01(\tR\apotType\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\"\xc5\x02\n" +
	"\n" +
	"RoundState\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x124\n" +
	"\x0fcommunity_cards\x18\x03 \x03(\v2\v.poker.CardR\x0ecommunityCards\x123\n" +
	"\x0fyour_hole_cards\x18\x04 \x03(\v2\v.poker.CardR\ryourHoleCards\x12$\n" +
	"\x0epot_size_cents\x18\x05 \x01(\x03R\fpotSizeCents\x12*\n" +
	"\x11current_bet_cents\x18\x06 \x01(\x03R\x0fcurrentBetCents\x12!\n" +
	"\fcurrent_turn\x18\a \x01(\x05R\vcurrentTurn\x12&\n" +
	"\x0fturn_expires_at\x18\b \x01(\tR\rturnExpiresAt\"\xe8\x02\n" +
	"\vTableUpdate\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\tR\aroundId\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x12!\n" +
	"\fcurrent_turn\x18\x03 \x01(\x05R\vcurrentTurn\x12*\n" +
	"\x11current_bet_cents\x18\x04 \x01(\x03R\x0fcurrentBetCents\x12$\n" +
	"\x0epot_size_cents\x18\x05 \x01(\x03R\fpotSizeCents\x124\n" +
	"\x0fcommunity_cards\x18\x06 \x03(\v2\v.poker.CardR\x0ecommunityCards\x12,\n" +
	"\aplayers\x18\a \x03(\v2\x12.poker.PlayerStateR\aplayers\x12&\n" +
	"\x0fturn_expires_at\x18\b \x01(\tR\rturnExpiresAt\x12'\n" +
	"\awinners\x18\t \x03(\v2\r.poker.WinnerR\awinners\"8\n" +
	"\x11ListTablesRequest\x12#\n" +
	"\rstatus_filter\x18\x01 \x01(\tR\fstatusFilter\":\n" +
	"\x12ListTablesResponse\x12$\n" +
	"\x06tables\x18\x01 \x03(\v2\f.poker.TableR\x06tables\"\xb6\x01\n" +
	"\x12CreateTableRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x11small_blind_cents\x18\x03 \x01(\x03R\x0fsmallBlindCents\x12&\n" +
	"\x0fbig_blind_cents\x18\x04 \x01(\x03R\rbigBlindCents\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\x05R\n" +
	"maxPlayers\"9\n" +
	"\x13CreateTableResponse\x12\"\n" +
	"\x05table\x18\x01 \x01(\v2\f.poker.TableR\x05table\"\x9c\x01\n" +
	"\x10JoinTableRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12-\n" +
	"\x13buy_in_amount_cents\x18\x03 \x01(\x03R\x10buyInAmountCents\x12%\n" +
	"\x0epreferred_seat\x18\x04 \x01(\x05R\rpreferredSeat\"\x8d\x01\n" +
	"\x11JoinTableResponse\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12#\n" +
	"\rseat_position\x18\x02 \x01(\x05R\fseatPosition\x12\x1f\n" +
	"\vstack_cents\x18\x03 \x01(\x03R\n" +
	"stackCents\x12\x17\n" +
	"\ahold_id\x18\x04 \x01(\tR\x06holdId\"G\n" +
	"\x11LeaveTableRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x8d\x01\n" +
	"\x12LeaveTableResponse\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12*\n" +
	"\x11final_stack_cents\x18\x02 \x01(\x03R\x0ffinalStackCents\x120\n" +
	"\x14settled_amount_cents\x18\x03 \x01(\x03R\x12settledAmountCents\"\x9f\x01\n" +
	"\x13PlayerActionRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x19\n" +
	"\bround_id\x18\x02 \x01(\tR\aroundId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12!\n" +
	"\famount_cents\x18\x05 \x01(\x03R\vamountCents\"B\n" +
	"\x14PlayerActionResponse\x12*\n" +
	"\x06update\x18\x01 \x01(\v2\x12.poker.TableUpdateR\x06update\"J\n" +
	"\x14GetTableStateRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x96\x01\n" +
	"\x15GetTableStateResponse\x12\"\n" +
	"\x05table\x18\x01 \x01(\v2\f.poker.TableR\x05table\x12!\n" +
	"\x05seats\x18\x02 \x03(\v2\v.poker.SeatR\x05seats\x126\n" +
	"\rcurrent_round\x18\x03 \x01(\v2\x11.poker.RoundStateR\fcurrentRound2\xaf\x03\n" +
	"\fPokerService\x12A\n" +
	"\n" +
	"ListTables\x12\x18.poker.ListTablesRequest\x1a\x19.poker.ListTablesResponse\x12D\n" +
	"\vCreateTable\x12\x19.poker.CreateTableRequest\x1a\x1a.poker.CreateTableResponse\x12>\n" +
	"\tJoinTable\x12\x17.poker.JoinTableRequest\x1a\x18.poker.JoinTableResponse\x12A\n" +
	"\n" +
	"LeaveTable\x12\x18.poker.LeaveTableRequest\x1a\x19.poker.LeaveTableResponse\x12G\n" +
	"\fPlayerAction\x12\x1a.poker.PlayerActionRequest\x1a\x1b.poker.PlayerActionResponse\x12J\n" +
	"\rGetTableState\x12\x1b.poker.GetTableStateRequest\x1a\x1c.poker.GetTableStateResponseB6Z4github.com/ChGSufro/sis-distribuidos-casino/poker/pbb\x06proto3"

var (
	file_pb_poker_proto_rawDescOnce sync.Once
	file_pb_poker_proto_rawDescData []byte
)

func file_pb_poker_proto_rawDescGZIP() []byte {
	file_pb_poker_proto_rawDescOnce.Do(func() {
		file_pb_poker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_poker_proto_rawDesc), len(file_pb_poker_proto_rawDesc)))
	})
	return file_pb_poker_proto_rawDescData
}

var file_pb_poker_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_pb_poker_proto_goTypes = []any{
	(*Card)(nil),                  // 0: poker.Card
	(*Table)(nil),                 // 1: poker.Table
	(*Seat)(nil),                  // 2: poker.Seat
	(*PlayerState)(nil),           // 3: poker.PlayerState
	(*Winner)(nil),                // 4: poker.Winner
	(*RoundState)(nil),            // 5: poker.RoundState
	(*TableUpdate)(nil),           // 6: poker.TableUpdate
	(*ListTablesRequest)(nil),     // 7: poker.ListTablesRequest
	(*ListTablesResponse)(nil),    // 8: poker.ListTablesResponse
	(*CreateTableRequest)(nil),    // 9: poker.CreateTableRequest
	(*CreateTableResponse)(nil),   // 10: poker.CreateTableResponse
	(*JoinTableRequest)(nil),      // 11: poker.JoinTableRequest
	(*JoinTableResponse)(nil),     // 12: poker.JoinTableResponse
	(*LeaveTableRequest)(nil),     // 13: poker.LeaveTableRequest
	(*LeaveTableResponse)(nil),    // 14: poker.LeaveTableResponse
	(*PlayerActionRequest)(nil),   // 15: poker.PlayerActionRequest
	(*PlayerActionResponse)(nil),  // 16: poker.PlayerActionResponse
	(*GetTableStateRequest)(nil),  // 17: poker.GetTableStateRequest
	(*GetTableStateResponse)(nil), // 18: poker.GetTableStateResponse
}
var file_pb_poker_proto_depIdxs = []int32{
	0,  // 0: poker.RoundState.community_cards:type_name -> poker.Card
	0,  // 1: poker.RoundState.your_hole_cards:type_name -> poker.Card
	0,  // 2: poker.TableUpdate.community_cards:type_name -> poker.Card
	3,  // 3: poker.TableUpdate.players:type_name -> poker.PlayerState
	4,  // 4: poker.TableUpdate.winners:type_name -> poker.Winner
	1,  // 5: poker.ListTablesResponse.tables:type_name -> poker.Table
	1,  // 6: poker.CreateTableResponse.table:type_name -> poker.Table
	6,  // 7: poker.PlayerActionResponse.update:type_name -> poker.TableUpdate
	1,  // 8: poker.GetTableStateResponse.table:type_name -> poker.Table
	2,  // 9: poker.GetTableStateResponse.seats:type_name -> poker.Seat
	5,  // 10: poker.GetTableStateResponse.current_round:type_name -> poker.RoundState
	7,  // 11: poker.PokerService.ListTables:input_type -> poker.ListTablesRequest
	9,  // 12: poker.PokerService.CreateTable:input_type -> poker.CreateTableRequest
	11, // 13: poker.PokerService.JoinTable:input_type -> poker.JoinTableRequest
	13, // 14: poker.PokerService.LeaveTable:input_type -> poker.LeaveTableRequest
	15, // 15: poker.PokerService.PlayerAction:input_type -> poker.PlayerActionRequest
	17, // 16: poker.PokerService.GetTableState:input_type -> poker.GetTableStateRequest
	8,  // 17: poker.PokerService.ListTables:output_type -> poker.ListTablesResponse
	10, // 18: poker.PokerService.CreateTable:output_type -> poker.CreateTableResponse
	12, // 19: poker.PokerService.JoinTable:output_type -> poker.JoinTableResponse
	14, // 20: poker.PokerService.LeaveTable:output_type -> poker.LeaveTableResponse
	16, // 21: poker.PokerService.PlayerAction:output_type -> poker.PlayerActionResponse
	18, // 22: poker.PokerService.GetTableState:output_type -> poker.GetTableStateResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pb_poker_proto_init() }
func file_pb_poker_proto_init() {
	if File_pb_poker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_poker_proto_rawDesc), len(file_pb_poker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_poker_proto_goTypes,
		DependencyIndexes: file_pb_poker_proto_depIdxs,
		MessageInfos:      file_pb_poker_proto_msgTypes,
	}.Build()
	File_pb_poker_proto = out.File
	file_pb_poker_proto_goTypes = nil
	file_pb_poker_proto_depIdxs = nil
}
